// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kjlRKdjtyuIYAjzOB59BLYxGQOWNq-0',
    appId: '1:88205953128:web:28df41c49798b7e19413dd',
    messagingSenderId: '88205953128',
    projectId: 'grab-clone-192e4',
    authDomain: 'grab-clone-192e4.firebaseapp.com',
    storageBucket: 'grab-clone-192e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe2vZSbCigf6vHJTXn4xQiHibxaZh0gM',
    appId: '1:88205953128:android:9e08cabb23fb1f139413dd',
    messagingSenderId: '88205953128',
    projectId: 'grab-clone-192e4',
    storageBucket: 'grab-clone-192e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrpOXwv7ZpPmm1V1Zjq0cIjVm3Oj6oNU',
    appId: '1:88205953128:ios:36f7f5a8a2ba3ea29413dd',
    messagingSenderId: '88205953128',
    projectId: 'grab-clone-192e4',
    storageBucket: 'grab-clone-192e4.appspot.com',
    iosClientId: '88205953128-ufoobin5gi9vpnhsbdf5bj7nt3fm9dm3.apps.googleusercontent.com',
    iosBundleId: 'com.daiplg.grabClone',
  );
}
